(() => {
 'use strict';
 const D=window.MUSEUM_DATA, app=document.querySelector('#app'), page=document.body.dataset.page;
 const dialog=document.querySelector('#detail-dialog'), content=document.querySelector('#dialog-content');
 const byId=new Map(D.catalog.map(a=>[a.id,a]));
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const normalize=s=>String(s??'').toLowerCase().replace(/\s+/g,'');
 let team=null,items=[],state={checked:{},notes:{},unavailable:{},extraIds:[],extraCustom:{}},category='전체',query='',status='all',activeId=null,storageOK=true,timer;
 let audit={};
 function read(key,fallback){try{const v=JSON.parse(localStorage.getItem(key));return v&&typeof v==='object'&&!Array.isArray(v)?v:fallback;}catch{storageOK=false;return fallback;}}
 function write(key,v){try{localStorage.setItem(key,JSON.stringify(v));return true;}catch{storageOK=false;toast('기기에 저장할 수 없습니다. 기록 파일을 내려받아 보관하세요.');return false;}}
 function toast(s){document.querySelector('#toast').textContent=s;clearTimeout(timer);timer=setTimeout(()=>document.querySelector('#toast').textContent='',3300);}
 function persist(){return write('cho-quest:'+D.version+':team'+team.id,state);}
 function download(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function openDialog(title){document.querySelector('#dialog-title').textContent=title;dialog.showModal();}
 function imageMarkup(a,cls='artifact-image'){return `<img class="${cls}" src="${esc(a.image)}" alt="${esc(a.name+' · '+a.collectionNumber)}" loading="lazy"><span class="image-error" hidden>사진을 열 수 없습니다. 공식 출처에서 확인하세요.</span>`;}
 document.addEventListener('error',e=>{if(e.target instanceof HTMLImageElement){e.target.hidden=true;const alt=e.target.nextElementSibling;if(alt?.classList.contains('image-error'))alt.hidden=false;}},true);
 document.querySelector('[data-close]').addEventListener('click',()=>dialog.close());
 dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
 dialog.addEventListener('close',()=>{activeId=null;});
 function home(){
 const hero=byId.get('nmk-159727');
 const homeIntros=['선사의 도구에서 시작해<br>새로운 시대를 만나요','조선의 공예에서 시작해<br>아름다움의 단서를 찾아요','세계의 보물에서 시작해<br>문화가 만나는 순간을 찾아요','청자의 푸른 빛에서 시작해<br>보물 속 이야기를 모아요'];
 app.innerHTML=`<section class="hero"><div><p class="eyebrow">2026 CHO 부문 워크샵 · 국립중앙박물관</p><h1>시간을 건너,<br><em>보물을 발견하다.</em></h1><p class="hero-copy">하나의 박물관, 서로 다른 네 개의 여정<br>우리 조만의 보물 이야기를 기록해보세요</p></div><figure class="hero-art">${imageMarkup(hero,'hero-image')}<figcaption class="art-caption"><b>금관총 금관</b><span>신라 · 본관9435</span></figcaption></figure></section><div class="stats"><div class="stat"><strong>4</strong><span>개의 탐험대</span></div><div class="stat"><strong>30</strong><span>가지 찾는 보물</span></div><div class="stat"><strong>7</strong><span>개의 시대·지역 분류</span></div><div class="stat"><strong>48</strong><span>종의 전체 유물</span></div></div><section id="teams"><div class="section-head"><h2>우리의 탐험을 시작할까요?</h2></div><div class="team-grid">${D.teams.map(t=>`<a class="team-card" href="team${t.id}_mission.html" style="--team-color:${t.color}"><div class="team-top"><span class="team-num">0${t.id}</span><span style="font-size:11px">${t.id}조 ↗</span></div><h3>${t.name}</h3><p>${homeIntros[t.id-1]}</p><div class="team-foot"><span>${t.route[0]}부터 출발</span></div></a>`).join('')}</div></section><section class="brief" id="how"><div><p class="eyebrow">DISCOVER MORE, REMEMBER TOGETHER</p><h2>더 많이 탐험하고,<br>함께 기억해요.</h2></div><div class="steps"><div class="step"><span>01</span><h3>사진과 이름을 대조해요</h3><p>같은 이름의 유물도 있어요. 소장품번호까지 확인하면 더 정확합니다.</p></div><div class="step"><span>02</span><h3>발견한 보물을 기록해요</h3><p>관람을 완료하면 체크하고, 관찰 미션에서 발견한 내용을 메모하세요.</p></div><div class="step"><span>03</span><h3>우리 조의 도록을 완성해요</h3><p>찾은 보물과 메모를 모아 보고, 가장 기억에 남는 유물을 소개하세요.</p></div></div></section><div class="notice">운영 안내 · 조별로 일부 유물을 함께 찾습니다. 행사일 전시 여부와 위치를 운영자가 확인한 뒤 미션을 진행해 주세요. 진행 기록은 이 기기·브라우저에 저장됩니다.</div>`;
 }
 function mission(){
 team=D.teams[Number(page.match(/team(\d)/)[1])-1];items=team.items.map(id=>byId.get(id));document.documentElement.style.setProperty('--accent',team.color);
 const saved=read('cho-quest:'+D.version+':team'+team.id,{});
 for(const key of ['checked','notes','unavailable'])state[key]=saved[key]&&typeof saved[key]==='object'&&!Array.isArray(saved[key])?saved[key]:{};
 state.extraCustom=saved.extraCustom&&typeof saved.extraCustom==='object'&&!Array.isArray(saved.extraCustom)?saved.extraCustom:{};
 state.extraIds=Array.isArray(saved.extraIds)?saved.extraIds.filter(id=>(byId.has(id)||state.extraCustom[id])&&!items.some(a=>a.id===id)):[];
 for(const a of items){if(typeof state.notes[a.id]!=='string')delete state.notes[a.id];if(state.checked[a.id])delete state.unavailable[a.id];}
 app.innerHTML=`<section class="page-head"><div><p class="eyebrow">TEAM 0${team.id} · ${team.english}</p><h1>${team.id}조, ${team.name}</h1><p>${team.intro}</p></div><div class="progress-box"><div class="progress-title">우리 조의 발견 <span id="progress-percent">0%</span></div><div class="progress-number"><span id="found-count">0</span><small> / 30</small></div><div class="progress-bar" role="progressbar" aria-label="관람 완료" aria-valuemin="0" aria-valuemax="30" aria-valuenow="0"><span id="progress-fill" style="width:0%"></span></div></div></section><div class="route"><b>추천 탐색 순서</b>${team.route.map((r,i)=>`<span>${i?'→ ':''}${r}</span>`).join('')}</div><p class="help-note">분류 순서에 맞춘 탐색 제안입니다. 실제 전시실 이동은 현장 안내도를 참고하세요.</p><div class="toolbar"><label class="search"><span aria-hidden="true">⌕</span><input id="search" type="search" aria-label="유물 검색" placeholder="유물명, 시대, 소장품번호, 전시위치 검색"></label><select id="status" aria-label="관람 상태"><option value="all">모든 미션</option><option value="pending">아직 못 찾은 보물</option><option value="done">발견한 보물</option><option value="unavailable">현장 확인 요청</option></select><button id="summary" class="secondary">수집 도록 보기</button><button id="catalog-pdf" class="secondary">PDF 도록 만들기</button></div><section class="custom-add"><div><p class="eyebrow">ADD YOUR FIND</p><h2>못 찾은 보물이 있다면</h2><p class="help-note">마음에 드는 유물을 검색해 우리 조 도록에 추가하세요.</p></div><div class="custom-search-row"><label class="search custom-search"><span aria-hidden="true">⌕</span><input id="custom-query" type="search" aria-label="도록에 추가할 유물 검색" placeholder="유물명·시대·소장품번호 검색"></label><button id="custom-api-search" class="secondary" type="button">공공 API 검색</button></div><div id="custom-results" class="custom-results"></div></section><div class="chips" role="group" aria-label="카테고리 선택">${['전체',...D.categories].map((c,i)=>`<button class="chip ${i===0?'active':''}" data-category="${esc(c)}" aria-pressed="${i===0}">${c} <span>${i===0?30:items.filter(a=>a.category===c).length}</span></button>`).join('')}</div><div class="results-row"><span id="results-count"></span><span id="save-indicator">이 기기에 자동 저장</span></div><div class="artifact-grid" id="grid"></div><div class="bottom-actions"><button id="export" class="secondary">기록 내려받기 ↓</button><div><button id="print" class="quiet">미션 인쇄</button><button id="reset" class="quiet">진행 기록 초기화</button></div></div><div class="notice">유물의 전시는 교체될 수 있습니다. 찾을 수 없다면 자세히 보기에서 ‘현장 확인 요청’을 남겨 주세요.</div>`;
 document.querySelector('#search').addEventListener('input',e=>{query=normalize(e.target.value);renderGrid();});
 document.querySelector('#status').addEventListener('change',e=>{status=e.target.value;renderGrid();});
 document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>{category=b.dataset.category;document.querySelectorAll('[data-category]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});renderGrid();}));
 document.querySelector('#summary').onclick=summary;
 document.querySelector('#catalog-pdf').onclick=printCatalog;
 document.querySelector('#custom-query').addEventListener('input',()=>renderCustomSearch(false));
 document.querySelector('#custom-api-search').onclick=()=>renderCustomSearch(true);
 document.querySelector('#export').onclick=exportState;
 document.querySelector('#print').onclick=()=>{if(category!=='전체'||query||status!=='all')toast('현재 화면에 표시된 미션만 인쇄됩니다.');window.print();};
 document.querySelector('#reset').onclick=()=>{activeId=null;content.innerHTML=`<p>${team.id}조의 이 기기에 저장된 관람 체크와 메모를 초기화합니다. 필요한 기록은 먼저 내려받아 주세요.</p><div class="dialog-actions"><button class="secondary" id="cancel-reset">돌아가기</button><button class="primary" id="confirm-reset">기록 초기화하기</button></div>`;document.querySelector('#cancel-reset').onclick=()=>dialog.close();document.querySelector('#confirm-reset').onclick=()=>{state={checked:{},notes:{},unavailable:{},extraIds:[],extraCustom:{}};persist();renderGrid();renderCustomSearch();dialog.close();toast('이 기기의 기록을 초기화했습니다.');};openDialog('진행 기록 초기화');};
 renderGrid();
 renderCustomSearch();
 }
 function asCatalogArtifact(row,detail={}){const get=name=>field(detail,name)||field(row,name);const id=get('id')||get('relicId')||('api-'+Date.now());const name=get('nameKr')||get('name')||get('relicName')||'이름 미상 유물';const relicNo=get('relicNo')||get('relicNoNm')||get('collectionNumber')||'소장품번호 미기재';const image=Object.entries({...row,...detail}).find(([k,v])=>/img|image|thumb|file/i.test(k)&&/^https?:\/\//.test(String(v||'')))?.[1]||'assets/0.jpg';return {id:'api-'+id,name,period:[get('nationalityName2')||get('nationalityName'),get('materialName2')].filter(Boolean).join(' · ')||get('period')||'공공 API 검색 결과',category:'추가 유물',collectionNumber:relicNo,material:get('materialName1')||get('material')||'미기재',size:get('size')||'미기재',location:get('exhRoomNm')||get('displayPlace')||'',image,source:get('url')||'https://www.emuseum.go.kr/',mission:'마음에 든 이유와 현장에서 본 단서를 짧게 기록해 보세요.',tagline:'우리 조가 고른 보물',aliases:[],originalNames:[name],notes:['공공 API 검색으로 도록에 추가한 유물입니다.']};}
function selectedItems(){return [...items,...state.extraIds.map(id=>byId.get(id)||state.extraCustom[id]).filter(Boolean)];}
function renderApiResults(holder,q,base,added){if(!q){return;}const apiBox=document.createElement('div');apiBox.className='api-extra-block';apiBox.textContent='공공 API에서 추가 유물을 검색 중…';holder.append(apiBox);apiCall('list?name='+encodeURIComponent(q)).then(records=>{const rows=records.filter(x=>!base.has('api-'+field(x,'id'))).slice(0,6);apiBox.innerHTML=rows.length?'<strong>공공 API 검색 결과</strong>':'<p class="help-note">공공 API 검색 결과가 없습니다.</p>';rows.forEach(row=>{const id=field(row,'id'),name=field(row,'nameKr')||field(row,'name')||'이름 미상 유물',relicNo=field(row,'relicNo')||'소장품번호 미기재';const button=document.createElement('button');button.className='custom-result';button.type='button';button.innerHTML=`<span class="api-thumb">API</span><span><b>${esc(name)}</b><small>${esc(relicNo)} · e뮤지엄 결과</small></span><em>${added.has('api-'+id)?'추가됨':'도록에 추가'}</em>`;button.disabled=added.has('api-'+id);button.onclick=async()=>{button.disabled=true;try{const detailRows=await apiCall('detail?id='+encodeURIComponent(id));const artifact=asCatalogArtifact(row,detailRows.find(r=>field(r,'id')===id)||detailRows[0]||{});state.extraCustom[artifact.id]=artifact;if(!state.extraIds.includes(artifact.id))state.extraIds.push(artifact.id);persist();renderCustomSearch();toast('API 검색 유물을 도록에 추가했습니다.');}catch(e){button.disabled=false;toast(e.message);}};apiBox.append(button);});}).catch(e=>{apiBox.innerHTML=`<p class="help-note">공공 API 검색을 사용할 수 없습니다. ${esc(e.message)}</p>`;});}
function renderCustomSearch(useApi=false){const input=document.querySelector('#custom-query'),holder=document.querySelector('#custom-results');if(!input||!holder)return;const q=normalize(input.value),added=new Set(state.extraIds),base=new Set(items.map(a=>a.id));const pool=D.catalog.filter(a=>!base.has(a.id)&&(!q||normalize([a.name,a.period,a.category,a.collectionNumber,a.location,a.aliases,...a.originalNames].join(' ')).includes(q))).slice(0,8);const addedItems=state.extraIds.map(id=>byId.get(id)||state.extraCustom[id]).filter(Boolean);holder.innerHTML=`${addedItems.length?`<div class="added-list"><strong>도록에 추가한 보물</strong>${addedItems.map(a=>`<span>${esc(a.name)} <button data-remove-extra="${a.id}" aria-label="${esc(a.name)} 도록에서 제거">×</button></span>`).join('')}</div>`:''}${q?pool.map(a=>`<button class="custom-result" data-add-extra="${a.id}" ${added.has(a.id)?'disabled':''}><img src="${esc(a.image)}" alt="${esc(a.name)}" loading="lazy"><span><b>${esc(a.name)}</b><small>${esc(a.period)} · ${esc(a.collectionNumber)}</small></span><em>${added.has(a.id)?'추가됨':'도록에 추가'}</em></button>`).join(''):'<p class="help-note">검색어를 입력하면 전체 후보 유물과 공공 API에서 찾아볼 수 있어요.</p>'}`;holder.querySelectorAll('[data-add-extra]').forEach(b=>b.onclick=()=>{if(!state.extraIds.includes(b.dataset.addExtra))state.extraIds.push(b.dataset.addExtra);persist();renderCustomSearch();toast('도록에 대체 보물을 추가했습니다.');});holder.querySelectorAll('[data-remove-extra]').forEach(b=>b.onclick=()=>{state.extraIds=state.extraIds.filter(id=>id!==b.dataset.removeExtra);delete state.extraCustom[b.dataset.removeExtra];persist();renderCustomSearch();toast('도록에서 제거했습니다.');});if(useApi)renderApiResults(holder,input.value.trim(),base,added);}
 function progress(){const count=items.filter(a=>state.checked[a.id]===true).length;document.querySelector('#found-count').textContent=count;document.querySelector('#progress-percent').textContent=Math.round(count/30*100)+'%';document.querySelector('#progress-fill').style.width=count/30*100+'%';document.querySelector('[role=progressbar]').setAttribute('aria-valuenow',String(count));document.querySelector('#save-indicator').textContent=storageOK?'이 기기에 자동 저장':'저장 불가 · 기록 내려받기 필요';return count;}
 function renderGrid(){
 progress();const visible=items.filter(a=>(category==='전체'||a.category===category)&&(!query||normalize([a.name,a.period,a.category,a.collectionNumber,a.location,a.aliases,...a.originalNames].join(' ')).includes(query))&&(status==='all'||status==='done'&&state.checked[a.id]===true||status==='pending'&&state.checked[a.id]!==true||status==='unavailable'&&state.unavailable[a.id]===true));
 document.querySelector('#results-count').textContent=`총 ${items.length}개 중 ${visible.length}개 표시`;
 document.querySelector('#grid').innerHTML=visible.length?visible.map(a=>{const done=state.checked[a.id]===true;return `<article class="artifact-card ${done?'done':''}" data-artifact="${a.id}"><div class="card-meta"><span class="serial">${String(items.indexOf(a)+1).padStart(2,'0')}</span><span class="badge">${a.curated?'엄선 목록':'시대 보완'}</span></div><button class="image-button" data-detail="${a.id}" aria-label="${esc(a.name)} 자세히 보기">${imageMarkup(a)}</button><div class="card-body"><div class="period">${esc(a.period)}</div><h3>${esc(a.name)}</h3><div class="collection">소장품번호 ${esc(a.collectionNumber)}</div><p class="card-mission">${esc(a.mission)}</p><div class="location">⌖ ${a.location?'공식 기재 위치 · '+esc(a.location):'전시위치 확인 필요'}</div>${state.unavailable[a.id]?'<div class="unavailable-label">현장 확인 요청 중</div>':''}<div class="card-actions"><button class="check-btn" data-check="${a.id}" aria-pressed="${done}" aria-label="${esc(a.name)} ${done?'발견 취소':'관람 완료'}">${done?'✓ 발견했어요':'＋ 관람 완료'}</button><button class="detail-btn" data-detail="${a.id}">자세히</button></div></div></article>`;}).join(''):'<div class="empty">해당하는 보물이 없습니다.<br>검색어나 카테고리를 바꿔 보세요.</div>';
 document.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>toggle(b.dataset.check));document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(b.dataset.detail));
 }
 function toggle(id){state.checked[id]=state.checked[id]!==true;if(state.checked[id])delete state.unavailable[id];persist();renderGrid();if(dialog.open&&activeId===id)updateDetailButtons();if(state.checked[id]&&progress()===30)toast('30개의 보물을 모두 발견했어요! 수집 도록을 열어보세요.');else toast(state.checked[id]?'보물을 발견했어요.':'관람 완료를 취소했어요.');document.querySelector(`[data-check="${id}"]`)?.focus({preventScroll:true});}
 function detail(id){
 activeId=id;const a=byId.get(id);
 content.innerHTML=`<div class="detail-layout"><div>${imageMarkup(a,'detail-image')}<p class="credits">사진 · 국립중앙박물관<br>${esc(a.collectionNumber)} · 공공누리 제1유형</p></div><div class="detail-info"><p class="eyebrow">${esc(a.category)} · OBJECT ${String(items.indexOf(a)+1).padStart(2,'0')}</p><h3>${esc(a.name)}</h3><dl><dt>국적·시대</dt><dd>${esc(a.period)}</dd><dt>소장품번호</dt><dd>${esc(a.collectionNumber)}</dd><dt>재질</dt><dd>${esc(a.material)}</dd><dt>크기</dt><dd>${esc(a.size)}</dd><dt>전시위치</dt><dd>${esc(a.location||'공식 기재 없음')}<br><span class="muted">행사일 전시 여부 재확인</span></dd></dl><a class="source-link" href="${esc(a.source)}" target="_blank" rel="noopener noreferrer">공식 소장품 상세 보기 ↗</a>${a.notes.map(n=>`<p class="inline-warning">${esc(n)}</p>`).join('')}</div></div><div class="mission-box"><strong>OBSERVATION · ${esc(a.tagline)}</strong><p>${esc(a.mission)}</p></div><label class="notes-label" for="note">우리 조의 관찰 메모</label><textarea id="note" maxlength="1500" placeholder="발견한 무늬, 인상적인 모습, 함께 나눈 이야기를 남겨보세요.">${esc(state.notes[id]||'')}</textarea><p class="save-status" id="note-status">이 기기에 자동 저장 · 최대 1,500자</p><div class="dialog-actions"><button class="secondary" id="unavailable">현장 확인 요청</button><button class="primary" id="detail-check">관람 완료</button></div>`;
 document.querySelector('#note').addEventListener('input',e=>{state.notes[id]=e.target.value;const ok=persist();document.querySelector('#note-status').textContent=ok?'메모 저장됨 · 이 기기에서 확인할 수 있어요.':'메모 저장 실패 · 기록 내려받기를 이용하세요.';});
 document.querySelector('#detail-check').onclick=()=>toggle(id);
 document.querySelector('#unavailable').onclick=()=>{if(state.checked[id]){toast('관람 완료를 취소한 뒤 현장 확인을 요청해 주세요.');return;}state.unavailable[id]=!state.unavailable[id];persist();renderGrid();updateDetailButtons();toast(state.unavailable[id]?'이 기기에 기록했습니다. 운영자에게 직접 알려 주세요.':'현장 확인 요청을 취소했습니다.');};
 updateDetailButtons();openDialog('보물 자세히 보기');
 }
 function updateDetailButtons(){document.querySelector('#detail-check').textContent=state.checked[activeId]?'✓ 발견했어요 · 취소':'＋ 관람 완료';document.querySelector('#detail-check').setAttribute('aria-pressed',String(state.checked[activeId]===true));document.querySelector('#unavailable').textContent=state.unavailable[activeId]?'현장 확인 요청 취소':'현장 확인 요청';}
 function summary(){activeId=null;const found=[...items.filter(a=>state.checked[a.id]===true),...state.extraIds.map(id=>byId.get(id)).filter(Boolean)];content.innerHTML=`<p class="help-note">${team.id}조가 발견하거나 도록에 추가한 보물 ${found.length}개 · 메모와 함께 돌아보세요.</p><div class="summary-list">${found.map(a=>`<article class="summary-item">${imageMarkup(a,'summary-image')}<h3>${esc(a.name)}</h3><div class="collection">${esc(a.collectionNumber)} · ${esc(a.category)}</div><p>${esc(state.notes[a.id]||'아직 관찰 메모가 없습니다.')}</p><a class="source-link" href="${esc(a.source)}" target="_blank" rel="noopener noreferrer">공식 출처 ↗</a></article>`).join('')||'<div class="empty">아직 발견한 보물이 없습니다.<br>관람한 유물을 체크해 보세요.</div>'}</div><div class="bottom-actions"><button class="primary" id="summary-pdf">PDF 도록 만들기</button><button class="secondary" id="summary-export">기록 JSON 내려받기 ↓</button></div>`;document.querySelector('#summary-export').onclick=exportState;document.querySelector('#summary-pdf').onclick=printCatalog;openDialog(`${team.id}조의 수집 도록`);}
 function exportState(){const payload={event:D.title,team:team.id,teamName:team.name,version:D.version,exportedAt:new Date().toISOString(),completed:items.filter(a=>state.checked[a.id]===true).length,total:30,extraCount:state.extraIds.length,items:selectedItems().map(a=>({name:a.name,id:a.id,collectionNumber:a.collectionNumber,category:a.category,checked:state.checked[a.id]===true,extra:state.extraIds.includes(a.id),unavailable:state.unavailable[a.id]===true,note:state.notes[a.id]||'',source:a.source,image:a.image}))};download(`CHO_${team.id}조_보물찾기_기록.json`,JSON.stringify(payload,null,2));toast('보물찾기 기록을 내려받았습니다.');}
 function printCatalog(){const rows=selectedItems().filter(a=>state.checked[a.id]===true||state.extraIds.includes(a.id));if(!rows.length){toast('도록에 담을 보물이 아직 없습니다. 발견 체크하거나 대체 보물을 추가해 주세요.');return;}const pages=[];for(let i=0;i<rows.length;i+=5)pages.push(rows.slice(i,i+5));const html=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><title>${team.id}조 도록</title><style>@page{size:A4;margin:16mm}*{box-sizing:border-box}body{font-family:Georgia,'Noto Serif KR','Malgun Gothic',serif;color:#151321;margin:0}.catalog-page{break-after:page;min-height:260mm}.catalog-page:last-child{break-after:auto}.catalog-head{display:flex;justify-content:space-between;align-items:end;border-bottom:1px solid #d8d2c8;padding-bottom:12px;margin-bottom:14px}.catalog-head h1{font-size:24px;margin:0}.catalog-head p{font-size:11px;color:#635d6d;margin:0}.catalog-item{display:grid;grid-template-columns:38mm 1fr;gap:12px;border-bottom:1px solid #e5ded3;padding:9px 0;min-height:43mm}.catalog-item img{width:38mm;height:38mm;object-fit:contain;background:#f7f4ef}.catalog-item h2{font-size:14px;margin:0 0 4px}.catalog-item .meta{font-size:10px;color:#6d6472;margin-bottom:6px}.catalog-item p{font-size:10.5px;line-height:1.65;margin:0 0 5px}.catalog-note{white-space:pre-wrap;color:#3d3746}.catalog-extra{font-size:9px;color:${team.color};font-weight:700;letter-spacing:.08em}</style></head><body>${pages.map((pageRows,idx)=>`<section class="catalog-page"><div class="catalog-head"><div><p>2026 CHO 부문 워크샵 · 국립중앙박물관</p><h1>${team.id}조 ${esc(team.name)} 도록</h1></div><p>${idx+1} / ${pages.length}</p></div>${pageRows.map(a=>`<article class="catalog-item"><img src="${esc(a.image)}" alt="${esc(a.name)}"><div><h2>${esc(a.name)}</h2><div class="meta">${esc(a.period)} · ${esc(a.collectionNumber)} · ${esc(a.category)} · ${esc(a.location||'전시위치 확인 필요')}</div><p>${esc(a.mission)}</p><p class="catalog-note">${esc(state.notes[a.id]||'관찰 메모 없음')}</p>${state.extraIds.includes(a.id)?'<div class="catalog-extra">ADDED TO CATALOG</div>':''}</div></article>`).join('')}</section>`).join('')}</body></html>`;const w=window.open('','_blank');if(!w){toast('팝업이 차단되었습니다. 브라우저 팝업 허용 후 다시 시도해 주세요.');return;}w.document.write(html);w.document.close();w.focus();setTimeout(()=>w.print(),300);toast('인쇄 창에서 PDF로 저장을 선택해 주세요.');}
 function organizer(){
 audit=read('cho-quest:'+D.version+':audit',{});
 app.innerHTML=`<section class="page-head"><div><p class="eyebrow">WORKSHOP DESK · ORGANIZER</p><h1>탐험을 준비하는 시간</h1><p>48종의 유물을 네 개 조에 배정했습니다. 행사일 전시 여부를 확인해 주세요.</p></div><a class="secondary" href="조별_유물배정표.csv" download>조별 배정표 CSV ↓</a></section><div class="notice">API 연결 상태 · 제공하신 키의 실제 목록 조회가 HTTP 429 / 코드 22(일일 요청 한도 초과)를 반환했습니다. 현재 48종의 이름·소장품번호·사진은 국립중앙박물관 공식 상세페이지에서 대조했습니다. API 조회 성공 및 행사일 전시는 아직 확인되지 않았습니다.</div><div class="admin-grid"><section class="admin-box"><h2>네 조, 같은 분류 비율</h2><table class="balance"><thead><tr><th>카테고리</th><th>조마다</th><th>비고</th></tr></thead><tbody>${D.categories.map((c,i)=>`<tr><td>${c}</td><td>${D.amounts[i]}개</td><td>${i===1?'고구려·백제·신라·가야 포함':i===5?'대한제국 1개, 현대 유물 별도 없음':i===4?'시대미상 소장본 1종은 지도 주제로 배정':''}</td></tr>`).join('')}<tr><th>합계</th><th>30개</th><td>조 안에 중복 없음</td></tr></tbody></table><p>CSV 49행을 중복 정리하고 인장 링크를 보완해 46종으로 반영했습니다. 고구려·가야 유물 2종을 보완해 전체 48종입니다. 네 조 사이에는 유물 중복이 있습니다.</p></section><section class="admin-box"><h2>120분 운영안 <small class="muted" style="font-size:12px">· 제안</small></h2><ol><li>10분 · 조별 집결, 역할 분담, 관람 수칙 안내</li><li>90분 · 유물 30개 탐색 및 관찰 메모</li><li>15분 · 조별 대표 보물 한 점씩 발표</li><li>5분 · 결과 정리와 마무리</li></ol><p>조별 대표 기기 하나로 기록하면 편리합니다. 다른 기기와 자동 동기화되지는 않습니다.</p><p>길잡이·관찰자·기록자·발표자 역할을 나누고, 이동은 뛰지 않고 전시실 관람 안내를 따라 진행하세요.</p></section></div><section class="admin-box"><h2>원본을 대조하며 수정한 내용</h2><ul><li>3행 ‘대한제국 황제의 인장’은 아미타불 링크였습니다. 주제에 맞춰 국새 칙명지보(신수241)를 선정했으며, 원래 의도한 인장인지는 최종 확인이 필요합니다.</li><li>16·24행, 18·39행, 21·34행은 각각 같은 유물로 병합했습니다.</li><li>‘백자 병’은 중국 송, ‘십이지상(말)’은 고려입니다. 금관총 금관과 서로 다른 두 반가사유상도 각각의 소장품번호로 고정했습니다.</li><li>대동여지도(건희3946)는 공식 제작시대가 시대미상입니다. 조선 지도 주제로만 배정했습니다.</li></ul><a class="source-link" href="원본목록_대조표.csv" download>49개 원본 행 대조표 내려받기 ↓</a></section><section style="margin-top:32px"><div class="section-head"><h2>행사일 전시 확인표</h2><p id="audit-count"></p></div><p class="help-note">공식 전시위치가 있는 유물 23종, 위치 미기재 25종입니다. 사진 매칭과 당일 전시는 별도 확인이 필요합니다. 아래 체크는 이 브라우저에만 저장되며 참가자 페이지를 변경하지 않습니다.</p><div class="toolbar"><label class="search"><input id="audit-search" type="search" aria-label="운영자 유물 검색" placeholder="유물명·소장품번호·카테고리 검색"></label><button class="secondary" id="audit-export">확인표 내려받기 ↓</button></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>행사일 확인</th><th>유물·소장품번호</th><th>카테고리 / 배정</th><th>공식 기재 위치</th><th>현장에서 확인한 위치·비고</th></tr></thead><tbody id="audit-body"></tbody></table></div></section><section class="admin-box" style="margin-top:32px"><h2>e뮤지엄 API 대조 도구</h2><p>API 한도 복구 후 로컬 서버에서 사용합니다. 검색 결과의 실제 ID로 상세 조회하며, 결과를 미션에 자동 반영하지 않습니다. 기관·소장품번호·명칭을 함께 대조하세요.</p><form class="api-form" id="api-form"><input id="api-query" aria-label="API 유물명 검색" placeholder="예: 농경문" maxlength="100" required><button class="primary" type="submit">API 검색</button></form><div id="api-results" aria-live="polite"></div><p class="credits">정적 HTML만 열면 API 검색은 사용할 수 없습니다. 실행 방법은 사용안내.md를 참고하세요. 인증키는 서버 환경변수로만 설정합니다.</p></section>`;
 document.querySelector('#audit-search').oninput=renderAudit;
 document.querySelector('#audit-export').onclick=()=>download('CHO_행사일_전시확인표.json',JSON.stringify({checkedAt:new Date().toISOString(),eventDate:'운영자 입력 필요',artifacts:D.catalog.map(a=>({id:a.id,name:a.name,collectionNumber:a.collectionNumber,officialLocation:a.location,checked:audit[a.id]?.checked===true,venueNote:audit[a.id]?.note||'',source:a.source}))},null,2));
 document.querySelector('#api-form').onsubmit=async e=>{e.preventDefault();await searchApi();};renderAudit();
 }
 function renderAudit(){const q=normalize(document.querySelector('#audit-search').value);document.querySelector('#audit-count').textContent=`${D.catalog.filter(a=>audit[a.id]?.checked===true).length} / 48종 확인`;
 document.querySelector('#audit-body').innerHTML=D.catalog.filter(a=>!q||normalize([a.name,a.collectionNumber,a.category].join(' ')).includes(q)).map(a=>`<tr><td><input type="checkbox" data-audit="${a.id}" aria-label="${esc(a.name)} 행사일 전시 확인" ${audit[a.id]?.checked?'checked':''}></td><td><img src="${esc(a.image)}" alt="${esc(a.name)}" class="tiny-image" loading="lazy"><a class="source-link" href="${esc(a.source)}" target="_blank" rel="noopener noreferrer">${esc(a.name)} ↗</a><br>${esc(a.collectionNumber)}${a.notes.length?'<p class="inline-warning">'+a.notes.map(esc).join('<br>')+'</p>':''}</td><td>${esc(a.category)}<br>${D.teams.filter(t=>t.items.includes(a.id)).map(t=>t.id+'조').join(' · ')}</td><td>${esc(a.location||'미기재')}<br><span class="muted">행사일 재확인</span></td><td><input class="location-edit" data-audit-note="${a.id}" aria-label="${esc(a.name)} 현장 위치 메모" maxlength="300" value="${esc(audit[a.id]?.note||'')}" placeholder="전시실·진열장·교체 여부"></td></tr>`).join('');
 document.querySelectorAll('[data-audit]').forEach(b=>b.onchange=()=>{audit[b.dataset.audit]={...audit[b.dataset.audit],checked:b.checked};write('cho-quest:'+D.version+':audit',audit);document.querySelector('#audit-count').textContent=`${D.catalog.filter(a=>audit[a.id]?.checked===true).length} / 48종 확인`;});document.querySelectorAll('[data-audit-note]').forEach(b=>b.oninput=()=>{audit[b.dataset.auditNote]={...audit[b.dataset.auditNote],note:b.value};write('cho-quest:'+D.version+':audit',audit);});
 }
 function xmlRecords(raw){const doc=new DOMParser().parseFromString(raw,'text/xml');if(doc.querySelector('parsererror'))throw Error('API XML을 읽을 수 없습니다.');const list=Array.from(doc.documentElement.children).find(x=>x.tagName.toLowerCase()==='list');if(!list)return [];return Array.from(list.children).map(node=>{const fields={};for(const child of node.children){if(child.hasAttribute('key'))fields[child.getAttribute('key')]=child.getAttribute('value')||child.textContent;else fields[child.tagName]=child.textContent;}return fields;});}
 async function apiCall(path){if(!/^https?:$/.test(location.protocol))throw Error('실행.cmd로 로컬 서버를 시작한 뒤 접속해 주세요.');const r=await fetch('/api/emuseum/'+path);const type=r.headers.get('content-type')||'';if(!type.includes('application/json'))throw Error('API 서버가 없습니다. 실행.cmd로 접속해 주세요.');const payload=await r.json();if(!r.ok)throw Error(payload.message||'API 요청을 처리하지 못했습니다.');return xmlRecords(payload.xml);}
 function field(x,name){const key=Object.keys(x).find(k=>k.toLowerCase()===name.toLowerCase());return key?x[key]:'';}
 async function searchApi(){const holder=document.querySelector('#api-results'),btn=document.querySelector('#api-form button');btn.disabled=true;holder.textContent='공공 API에서 조회 중…';try{const records=await apiCall('list?name='+encodeURIComponent(document.querySelector('#api-query').value.trim()));holder.replaceChildren();if(!records.length)holder.textContent='검색 결과가 없습니다.';for(const x of records){const id=field(x,'id');if(!/^PS01001001\d+$/.test(id))continue;const div=document.createElement('div');div.className='api-result';const title=document.createElement('strong');title.textContent=field(x,'nameKr')||field(x,'name');const text=document.createElement('div');text.textContent='API ID '+id+' · 소장품번호 '+field(x,'relicNo')+' · 기관코드 '+field(x,'museumCode');const button=document.createElement('button');button.className='secondary';button.textContent='이 ID로 상세 대조';button.onclick=async()=>{button.disabled=true;try{const rows=await apiCall('detail?id='+encodeURIComponent(id));const row=rows.find(r=>field(r,'id')===id);if(!row)throw Error('선택한 ID의 상세 결과가 없습니다.');const info=document.createElement('p');info.textContent=[field(row,'nameKr')||field(row,'name'),field(row,'museumName2'),field(row,'museumName3')+field(row,'relicNo'),field(row,'nationalityName2')].filter(Boolean).join(' · ');div.append(info);toast('명칭·기관·소장품번호를 원본 목록과 대조해 주세요.');}catch(e){toast(e.message);}finally{button.disabled=false;}};div.append(title,text,button);holder.append(div);}}catch(e){holder.textContent=e.message;}finally{btn.disabled=false;}}
 if(page==='index')home();else if(page==='organizer')organizer();else mission();
})();
